# See https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html

# Use container-based infrastructure
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  # When running scripted tests targeting multiple SBT versions, we must first publish locally for all SBT versions
  - sbt "^ publishLocal" "^ scripted"
