# See https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html

# Use container-based infrastructure
sudo: false

language: scala

# Ubuntu Trusty (https://docs.travis-ci.com/user/reference/trusty/)
dist: trusty

install:
  - git checkout -qf $TRAVIS_BRANCH

stages:
  - name: test
  - name: release
    if: (branch =~ /^release\/.*$/)

jobs:
  include:
    - stage: test
      # When running scripted tests targeting multiple SBT versions, we must first publish locally for all SBT versions
      script: sbt "^ publishLocal" "^ scripted"
    - stage: release
      # Extract release version from branch name
      env: export RELEASE_VERSION=`echo $TRAVIS_BRANCH | sed -r 's/^release\/(.*)$/\1/'`
      script: sbt "^ release release-version $RELEASE_VERSION with-defaults"

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
